Auto include nf.php
codecat/Nin pull request #16
Opened 2023-06-14 14:58 UTC by sylae

if nin is a Composer dependency, this will include nf.php for you :)

2023-06-14 16:50 UTC, codecat requested changes

2023-06-14 16:50 UTC, codecat commented on Readme.md
>  ```
This should still require you to include `vendor/autoload.php`, right? So we should probably put that info here!

2023-06-14 17:06 UTC, sylae commented on Readme.md
>  ```
oh good idea! whoops

2023-06-15 11:05 UTC, merged

2023-06-15 11:05 UTC, codecat commented
Thanks!